[workspace]
resolver = "3"
members = ["hyprfill", "hyprstash"]

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
hyprland = "0.4.0-beta.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
