[package]
name = "hyprstash"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
hyprland = "0.4.0-beta.3"
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
